### ISSUE TITLE
GUI mac 异常；CLI Linux 出现undefined symbol问题

### ISSUE THREAD

**Issue by rng0** [1024UNO/Downloads#2]
mac GUI软件打不开，直接报异常；centos 7.1 CLI出现undefined symbol:_ZN5boost15program_options3argB5cxx11E 问题；求开源代码

**Comment by 1024UNO** [comment]
mac GUI钱包，我在打包一下，更新一下。
cnetos 7.1 错误要你安装boost。原因我没有编译进去，应为减少大小。打包了50MB，不打包2.5MB 
源代码是开源的哇 。1024

**Comment by 1024UNO** [comment]
MAC GUI现在好了。
